.TH HFST-OSPELL-OFFICE "1" "January 2016" "hfst-ospell-office " "User Commands"
.SH NAME
hfst-ospell-office \- Spell checker tool based on HFST
.SH SYNOPSIS
.B hfst-ospell-office
[\fIOPTIONS\fR] \fIZHFST-ARCHIVE\fR
.SH DESCRIPTION
Use automata in ZHFST\-ARCHIVE or from OPTIONS to check and correct
.SH OPTIONS
.TP
\fB\-\-verbatim\fR
Check the input as-is without any transformations
.SH "REPORTING BUGS"
Report bugs to mail@tinodidriksen.com and/or hfst\-bugs@helsinki.fi
.PP
hfstospell 0.4.1
.br
Jan 11 2016 12:57:25
.br
Copyright (C) 2009 \- 2016 University of Helsinki
